import { useState, type ReactNode } from 'react'
import { profile, projects, skillGroups } from './data/profile'
import './project-actions.css'

const nav = ['About', 'Skills', 'Projects', 'Experience', 'Education', 'Contact']
const Arrow = () => <span aria-hidden="true">↗</span>

function ExternalLink({ href, children }: { href?: string; children: ReactNode }) {
  return href ? <a href={href} target="_blank" rel="noreferrer">{children} <Arrow /></a> : null
}

export default function App() {
  const [open, setOpen] = useState(false)
  const featured = projects.find((project) => project.featured) ?? projects[0]
  return <>
    <header className="nav"><a className="brand" href="#home">Godwin Edzer E<span>.</span></a><nav className={open ? 'open' : ''} aria-label="Primary navigation">{nav.map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setOpen(false)}>{item}</a>)}<a className="nav-resume" href={profile.resumeUrl} target="_blank" rel="noreferrer">View Resume <Arrow /></a></nav><button className="menu" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? '×' : '≡'}</button></header>
    <main>
      <section id="home" className="hero section"><div><p className="eyebrow">M.Sc. Computer Science · Software Developer</p><h1>Software Developer focused on full-stack development and machine learning.</h1><p className="lede">M.Sc. Computer Science graduate with practical experience in MERN-stack development, Python, REST APIs, MongoDB, machine learning, and application development.</p><div className="actions"><a className="button dark" href="#projects">View Projects <Arrow /></a><a className="button" href={profile.resumeUrl} target="_blank" rel="noreferrer">View Resume <Arrow /></a></div><div className="socials">{profile.github && <a href={profile.github} target="_blank" rel="noreferrer">GitHub <Arrow /></a>}<a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow /></a></div></div><aside className="terminal" aria-label="Technical areas"><div><i></i><i></i><i></i><b>godwin-edzer-e:~</b></div><pre>GODWIN-EDZER-E/<br/>├── frontend<br/>├── backend<br/>├── database<br/>├── machine-learning<br/>└── applications</pre><small>status: open_to_software_roles</small></aside></section>
      <section id="about" className="section split"><p className="section-tag">01 / ABOUT</p><div><h2>Full-stack applications and machine-learning projects.</h2><p>I am an M.Sc. Computer Science graduate with practical experience developing web applications using React.js, Node.js, Express.js, MongoDB, Python, and REST APIs. My projects also include machine-learning applications using XGBoost and SHAP.</p></div></section>
      <section id="skills" className="section"><p className="section-tag">02 / TECHNICAL SKILLS</p><h2>Technical skills.</h2><div className="skills">{Object.entries(skillGroups).map(([title, values]) => <article key={title}><h3>{title}</h3><div>{values.map(value => <span key={value}>{value}</span>)}</div></article>)}</div></section>
      <section id="projects" className="section"><p className="section-tag">03 / SELECTED PROJECTS</p><h2>Selected projects.</h2><article className="featured"><div className="project-meta">{featured.number}<br/><small>{featured.label}</small><br/><small>{featured.date}</small></div><div><h3>{featured.name}</h3><p>{featured.description}</p><ul>{featured.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><div className="architecture"><b>User Input</b><span>↓</span><b>React.js Frontend</b><span>↓</span><b>Node.js / Express.js</b><span>↓</span><b>Python / Flask ML Service</b><span>↓</span><b>XGBoost Model</b><span>↓</span><b>Prediction + SHAP Explainability</b></div><div className="project-actions"><a href={featured.github || profile.github} target="_blank" rel="noreferrer">GitHub ↗</a></div></div><div className="project-aside"><b>Model Evaluation</b>{featured.metrics && <ul>{featured.metrics.map(metric => <li key={metric}>{metric}</li>)}</ul>}</div></article><div className="project-list">{projects.filter((project) => !project.featured).map(project => <article className="project" key={project.name}><div className="project-meta">{project.number}<br/><small>{project.label}</small><br/><small>{project.date}</small></div><div><h3>{project.name}</h3><p>{project.description}</p><ul>{project.features.map(feature => <li key={feature}>{feature}</li>)}</ul><div className="project-actions"><a href={project.github || profile.github} target="_blank" rel="noreferrer">GitHub ↗</a></div></div><div className="project-aside"><div className="stack">{project.stack.map(item => <span key={item}>{item}</span>)}</div></div></article>)}</div></section>
      <section id="experience" className="section split"><p className="section-tag">04 / EXPERIENCE</p><div className="timeline"><article><p>May 2025 – Aug 2025</p><h3>Full Stack (MERN) Development Intern · BIGZIEL</h3><p>Developed full-stack web applications using the MERN stack, working with React.js, Node.js, Express.js, and MongoDB.</p><p>React.js · Node.js · Express.js · MongoDB · MERN Stack · REST APIs</p></article><article><p>May 2025 · Remote</p><h3>Python Intern · Konigtronics Private Limited</h3><p>Developed a movie review application using Python and the OMDb REST API.</p><p>Python · REST APIs</p></article></div></section>
      <section id="education" className="section split"><p className="section-tag">05 / EDUCATION</p><div className="education"><h2 className="degree">Master of Science, Computer Science</h2><p>Completed 2026 · Degree completed; certificate pending issuance.</p><p>SRM Arts and Science College, Kattankulathur</p><p>Affiliated to the University of Madras · CGPA: 8.53</p><br/><h2 className="degree">Bachelor of Computer Science</h2><p>2021 – 2024</p><p>SRM Arts and Science College, Kattankulathur</p><p>Affiliated to the University of Madras · CGPA: 7.73</p></div></section>
      <section id="contact" className="contact"><p className="section-tag">06 / CONTACT</p><h2>Interested in my background or projects?</h2><p>View my resume or contact me through email, GitHub, or LinkedIn.</p><div className="actions"><a className="button dark" href={`mailto:${profile.email}`}>Email me <Arrow /></a><a className="button" href={profile.resumeUrl} target="_blank" rel="noreferrer">View Resume <Arrow /></a></div></section>
    </main><footer><span>{profile.name}</span><div>{profile.github && <a href={profile.github}>GitHub</a>}<a href={profile.linkedin}>LinkedIn</a><a href={`mailto:${profile.email}`}>Email</a></div><small>© {new Date().getFullYear()} · Built with React + TypeScript</small></footer>
  </>
}
